Added automatic setup and config modularity
taberoajorge/saime-script pull request #2
Opened 2023-03-24 03:12 UTC by edseldim

I modified how the program is setup. Now, it uses a script called preparacion_python.bat to setup a virtual environment, download the necessary libraries (requests) and executes the script. Also, the project contains a config.json file where one can add all the required information for the script to execute and send an email among other things

2023-03-24 03:24 UTC, edseldim commented
Also, consider adding a branch called "developer" for contributions. Having to do a pull request to master is considered a bad practice 👍

2023-03-24 18:20 UTC, taberoajorge requested changes
Se actualizo el codigo, se require actualizar el PR

2023-03-24 18:28 UTC, taberoajorge requested changes
Tambien:

Agregar comentarios en el código para explicar los cambios realizados y cómo funcionan. Esto facilitará la comprensión del código para futuros colaboradores y desarrolladores.

2023-03-24 18:28 UTC, taberoajorge commented on saimebot.py
> +    logger = logging.basicConfig(
En la función logging.basicConfig(), podrías agregar un formato para el registro, lo que mejoraría la legibilidad de los registros. Por ejemplo:
```
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
```

2023-03-24 18:28 UTC, taberoajorge commented on saimebot.py
> +    logging.debug(str(global_config))
Es necesario el uso de logging.debug(str(global_config))? ya que podría contener información confidencial como contraseñas de aplicaciones.

2023-03-24 18:28 UTC, taberoajorge commented on saimebot.py
> +                print("No se puede enviar el correo porque falta configuración. Revise el archivo config.json (ignorando error...)")
En lugar de usar print para los mensajes de error, podrías  utilizar logging.error o logging.warning.

2023-03-24 18:28 UTC, taberoajorge commented on saimebot.py
> +                                                                   global_config["app_password"]]]): # añadir condiciones necesarias para mandar email
Estas línea que verifican si todas las condiciones necesarias para enviar el correo electrónico están configuradas es un poco difícil de leer. Podrías hacer una refactorización para mejorar la legibilidad. Por ejemplo:

```
email_config_ready = all([global_config["sender_email"], global_config["receiver_email"], global_config["app_password"]])

if not email_config_ready:
    print("No se puede enviar el correo porque falta configuración. Revise el archivo config.json (ignorando error...)")
else:
    send_email_notification(global_config["sender_email"], global_config["receiver_email"], global_config["app_password"])

```

2023-03-24 18:39 UTC, taberoajorge commented
Tambien de una vez apuntar hacia la developer branch

2023-03-24 18:57 UTC, edseldim commented on saimebot.py
> +    logging.debug(str(global_config))
Eso está hecho pra que cuando se esté debugeando, se pueda ver qué datos entran del config. No se vería en producción

2023-03-24 18:58 UTC, edseldim commented on saimebot.py
> +                print("No se puede enviar el correo porque falta configuración. Revise el archivo config.json (ignorando error...)")
A partir del comentario anterior, se está usando debugging para separar aquellos mensajes que son para los desarrolladores y prints para los mensajes del usuario final, básicamente para seguir buenas practicas

2023-03-25 00:21 UTC, edseldim commented
Acabo de hacer todos los cambios pedidos!

2023-03-25 14:18 UTC, merged